config/routes.rb
Myapp::Application.routes.draw do
  get "home/landing"
  post "home/create_subscriber"

  root to: 'home#landing'

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates_presence_of :email, message: 'Please enter your email address.'
  validates_uniqueness_of :email, message: 'That email is already on the subscription list.'
  validates_format_of :email,
    with: /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/i,
    message: 'Please use a valid email address.'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def landing
    @subscriber = Subscriber.new
  end

  def create_subscriber
    @subscriber = Subscriber.new(params[:subscriber].permit(:email))

    if @subscriber.save
      flash[:success] = "You have been subscribed"
      redirect_to root_path
    else
      flash[:error] = "You have entered an invalid email"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="header header-landing">
  <div class="header-text">
    <h1 class="header-title"><b>Cutesy Putsy</b></h1>
    <h3>For All Your Cutesy Shit</h3>
    <br>
    <a href="#intro" class="btn btn-large btn-default landing">About</a>
    <a href="#" class="btn btn-large btn-default landing">Blog</a>
    <a href="https://instagram.com/cutesyputsy/" target="_blank" class="btn btn-large btn-default landing">Instagram</a>
  </div>
</div>

<div id="intro" class="intro">
  <div class="container">
    <div class="row col-md-8 col-md-offset-2">
      <h1 class="section-title"><b>Section 1</b></h1>
      <br>
      <p>Lorem Ipsum</p>
    </div>
  </div>
</div>
<hr class="dark">
<div id="elaborate" class="intro">
  <div class="container">
    <div class="row col-md-8 col-md-offset-2">
      <h1 class="section-title"><b>Section 2</b></h1>
      <br>
      <p>Lorem Ipsum</p>
    </div>
  </div>
</div>
<hr class="dark">
<div id="contact" class="intro">
  <div class="container">
    <div class="row col-md-8 col-md-offset-2">
      <h1 class="section-title"><b>Section 3</b></h1>
      <br>
      <p>Lorem Ipsum</p>
    </div>
  </div>
</div>
<hr class="dark">
<div id="contact" class="intro">
  <div class="container">
    <div class="row col-md-6 col-md-offset-3">
      <a href="#" target="_blank"><i class="fa fa-facebook-official fa-4x dark-icon"></i></a>
      <a href="https://instagram.com/cutesyputsy/" target="_blank"><i class="fa fa-instagram fa-4x dark-icon"></i></a>
      <a href="mailto:cutesyputsy@gmail.com" target="_top"><i class="fa fa-envelope fa-4x dark-icon"></i></a>
      <p>&copy Peihong Li 2014</p>
    </div>
  </div>
</div>

app/views/home/landing.html.erb
<div class="header header-landing">
  <div class="header-text">
    <h1 class="header-title"><b>Cutesy Putsy</b></h1>
    <h3>For All Your Cutesy Shit</h3>
    <br>
    <%= form_for @subscriber, url: home_create_subscriber_path do |f| %>
      <%= f.text_field :email, class: 'header-field', placeholder: 'Email' %>
      <br>
      <br>
      <%= link_to 'About', '#intro', class: 'btn btn-large btn-default btn-landing' %>
      <%= link_to 'Instagram', 'https://instagram.com/cutesyputsy', class: 'btn btn-large btn-default btn-landing' %>
      <%= f.submit 'Subscribe', class: 'btn btn-large btn-default btn-subscribe' %>
    <% end %>
  </div>
</div>

<div id="intro" class="intro">
  <div class="container">
    <div class="row col-md-8 col-md-offset-2">
      <h1 class="section-title"><b>Section 1</b></h1>
      <br>
      <p>Lorem Ipsum</p>
    </div>
  </div>
</div>
<hr class="dark">
<div id="elaborate" class="intro">
  <div class="container">
    <div class="row col-md-8 col-md-offset-2">
      <h1 class="section-title"><b>Section 2</b></h1>
      <br>
      <p>Lorem Ipsum</p>
    </div>
  </div>
</div>
<hr class="dark">
<div id="contact" class="intro">
  <div class="container">
    <div class="row col-md-8 col-md-offset-2">
      <h1 class="section-title"><b>Section 3</b></h1>
      <br>
      <p>Lorem Ipsum</p>
    </div>
  </div>
</div>
<hr class="dark">
<div id="contact" class="intro">
  <div class="container">
    <div class="row col-md-6 col-md-offset-3">
      <a href="#" target="_blank"><i class="fa fa-facebook-official fa-4x dark-icon"></i></a>
      <a href="https://instagram.com/cutesyputsy/" target="_blank"><i class="fa fa-instagram fa-4x dark-icon"></i></a>
      <a href="mailto:cutesyputsy@gmail.com" target="_top"><i class="fa fa-envelope fa-4x dark-icon"></i></a>
      <p>&copy Peihong Li 2014</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DigitalOcean Rails Application</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>